### PR TITLE
Bunch of small fixes

### LINKED ISSUE #698: Redirect to Portfolio page after buying on SimpleUI

### LINKED ISSUE #705: Change Open Positions Tab name Or Merge tabs?
"In the Portfolio tab, Open Positions, is this referring to all open positions or only bought options? Because I am also seeing a tab written options. Are you offering portfolio margin, netting?"

### LINKED ISSUE #707: Breakeven says $NaN for Market Order
- [ ] Breakeven says $NaN for Market Order on main market Buy/Sell dialog
- [ ] Simple UI, instead of showing a dash, say "market price"

### LINKED ISSUE #708: Disable Place Order in SimpleUI when no Asks

### PR DESCRIPTION
**Pull request by jasonchitla**
- Redirect to Portfolio page after buying on SimpleUI, closes #698 
- Breakeven says $NaN for Market Order, closes #707 
- Disable Place Order in SimpleUI when no Asks, closes #708 
- Change Open Positions Tab name Or Merge tabs?, closes #705

### CODE REVIEW

File: src/components/Markets/MarketsUnsettledBalances.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ const MarketsUnsettledBalances: React.FC = () => {
       fontSize={'14px'}
       px={[1, 1, 0]}
     >
-      <Box px={[1, 1, 0]}>Unsettled Balances:</Box>
```
Comment (tomjohn1028) [inline src/components/Markets/MarketsUnsettledBalances.tsx:31]: @jasonchitla Should we rename this to "Funds locked in Serum". Or something a little bit more explanatory? We get so many questions around unsettled balances and the nomenclature probably doesn't help.

Maybe even an info icon would help

File: src/components/UnsettledBalancesTable/UnsettledBalancesTable.tsx [hunk 2]
```diff
@@ -45,7 +45,7 @@ const UnsettledBalancesTable = () => {
                 colSpan={9}
                 className={classes.headCell}
               >
-                <h3 style={{ margin: 0 }}>Unsettled Balances</h3>
+                <h3 style={{ margin: 0 }}>Unsettled Funds</h3>
```
Comment (tomjohn1028) [inline src/components/UnsettledBalancesTable/UnsettledBalancesTable.tsx:48]: Same thing as here https://github.com/mithraiclabs/psyoptions-frontend/pull/710/files#r742389912

**Review by tomjohn1028 — APPROVED** [review]

**Comment by jasonhargrove** [comment]
Code looks clean, and 100% support copy changes that reveal more into process, in the simplest terms
